Modify IVHD to accept existing k-NN instead of training a new one
IVHD/IVHD pull request #17
Opened 2024-06-18 20:27 UTC by AdrianBesciak

Modify IVHD and Gradient IVHD to accept existing k-NN and not train a new one.

Closes #6

2024-06-18 21:01 UTC, mjste requested changes
The issue is described as follows: you need to pass precomputed graph of nearest neighbors (i.e. list of indices). What this PR does is just passing fitted knn object, which in case of knn, means just an object which remembers original set. Computation is not performed until `knn_model.kneighbors(X)`.

2024-06-18 22:03 UTC, AdrianBesciak commented
@mjste Done

2024-06-19 06:09 UTC, mjste reviewed
Could you add checking if passed neighbors graph has correct shape? Currently it is possible to pass any neighbor indices list, with different dimension that was requested in class constructor

2024-06-20 20:43 UTC, mjste approved these changes

2024-06-20 21:08 UTC, merged